### ISSUE TITLE
Compile time asserts

### ISSUE THREAD

**Issue by ollpu** [golddranks/recycle_vec#2]
When `const_panic` first stabilized, it didn't seem to be applicable for checking properties of generics, since const items inside functions can't be tied to the generics. However, an associated const on a struct seems to do the trick:

```rust
use std::mem::{align_of, size_of};

struct AssertSameLayout<A, B>(std::marker::PhantomData<(A, B)>);
impl<A, B> AssertSameLayout<A, B> {
    const OK: () = assert!(
        size_of::<A>() == size_of::<B>() && align_of::<A>() == align_of::<B>(),
        "types must have identical size and alignment"
    );
}

// used as
() = AssertSameLayout::<A, B>::OK;
```

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7f401b74faed4a76c098f86cc60a2f86)

Idea stolen from [here](https://github.com/near/nearcore/blob/master/utils/stdx/src/lib.rs#L144).

**Comment by golddranks** [comment]
Oh, interesting!! Thanks for the pointer.

**Comment by golddranks** [comment]
Thank you! I implemented static asserts. This also means that might be possible to get forward with getting this to stdlib.
